[2025-04-20T11:20:31.381+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-20T11:20:31.408+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_vehicules_spark.run_spark_pipeline manual__2025-04-20T11:20:28.569696+00:00 [queued]>
[2025-04-20T11:20:31.420+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_vehicules_spark.run_spark_pipeline manual__2025-04-20T11:20:28.569696+00:00 [queued]>
[2025-04-20T11:20:31.422+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-20T11:20:31.445+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_spark_pipeline> on 2025-04-20 11:20:28.569696+00:00
[2025-04-20T11:20:31.454+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=491) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-20T11:20:31.456+0000] {standard_task_runner.py:72} INFO - Started process 493 to run task
[2025-04-20T11:20:31.458+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pipeline_vehicules_spark', 'run_spark_pipeline', 'manual__2025-04-20T11:20:28.569696+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_***.py', '--cfg-path', '/tmp/tmpf2pl94tj']
[2025-04-20T11:20:31.460+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask run_spark_pipeline
[2025-04-20T11:20:31.538+0000] {task_command.py:467} INFO - Running <TaskInstance: pipeline_vehicules_spark.run_spark_pipeline manual__2025-04-20T11:20:28.569696+00:00 [running]> on host 27ba6aa397b3
[2025-04-20T11:20:31.686+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cheick' AIRFLOW_CTX_DAG_ID='pipeline_vehicules_spark' AIRFLOW_CTX_TASK_ID='run_spark_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T11:20:28.569696+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-20T11:20:28.569696+00:00'
[2025-04-20T11:20:31.689+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-20T11:20:31.690+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-20T11:20:31.691+0000] {logging_mixin.py:190} INFO - Current task name:run_spark_pipeline state:running start_date:2025-04-20 11:20:31.409123+00:00
[2025-04-20T11:20:31.691+0000] {logging_mixin.py:190} INFO - Dag name:pipeline_vehicules_spark and current dag run status:running
[2025-04-20T11:20:31.692+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-20T11:20:31.693+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-20T11:20:31.695+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master spark://spark-master:7077 /app/scripts/car_pipeline_spark.py']
[2025-04-20T11:20:31.714+0000] {subprocess.py:99} INFO - Output:
[2025-04-20T11:20:31.717+0000] {subprocess.py:106} INFO - /usr/bin/bash: line 1: spark-submit: command not found
[2025-04-20T11:20:31.718+0000] {subprocess.py:110} INFO - Command exited with return code 127
[2025-04-20T11:20:31.738+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-04-20T11:20:31.752+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-20T11:20:31.753+0000] {logging_mixin.py:190} INFO - Task start:2025-04-20 11:20:31.409123+00:00 end:2025-04-20 11:20:31.751331+00:00 duration:0.342208
[2025-04-20T11:20:31.754+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): run_spark_pipeline> dag:<DAG: pipeline_vehicules_spark> dagrun:<DagRun pipeline_vehicules_spark @ 2025-04-20 11:20:28.569696+00:00: manual__2025-04-20T11:20:28.569696+00:00, state:running, queued_at: 2025-04-20 11:20:28.588733+00:00. externally triggered: True>
[2025-04-20T11:20:31.755+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 127.
[2025-04-20T11:20:31.756+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=pipeline_vehicules_spark, task_id=run_spark_pipeline, run_id=manual__2025-04-20T11:20:28.569696+00:00, execution_date=20250420T112028, start_date=20250420T112031, end_date=20250420T112031
[2025-04-20T11:20:31.811+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-20T11:20:31.812+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task run_spark_pipeline (Bash command failed. The command returned a non-zero exit code 127.; 493)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-04-20T11:20:31.873+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-20T11:20:31.905+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-20T11:20:31.910+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
